/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.Modulo_Conexão;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author aldac
 */
public class Cadastro_Livro extends javax.swing.JFrame {
    Connection conexao = null; //Variavel de conexao 
    PreparedStatement pst = null; //Variavel de execução das sql
    ResultSet rs = null; //Variavel para exibir resultados
    
    public void cadastrar(){
        String sql_cadastro = "insert into livros(nome,editora,autor,genero,numero,ilustrador) values(?,?,?,?,?,?)";
        
        try {
            pst = conexao.prepareStatement(sql_cadastro);
            pst.setString(1, JT_nome.getText());
            pst.setString(2, JT_editora.getText());
            pst.setString(3, JT_autor.getText());
            pst.setString(4, JT_genero.getText());
            pst.setString(5, JT_numero.getText());
            pst.setString(6, JT_ilustrador.getText());
            int adcionado = pst.executeUpdate();
            
            if(adcionado>0){
                JT_nome.setText("");
                JT_editora.setText("");
                JT_autor.setText("");
                JT_genero.setText("");
                JT_numero.setText("");
                JT_ilustrador.setText("");
                
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
            }else{
                JOptionPane.showMessageDialog(null, "Erro no cadastro");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setIcon(){
            
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/icon.png")));
        
    }
    /**
     * Creates new form Cadastro_Livro
     */
    public Cadastro_Livro() {
        initComponents();
        conexao = Modulo_Conexão.conector();
        
        setIcon();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JT_nome = new javax.swing.JTextField();
        JT_autor = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        JT_ilustrador = new javax.swing.JTextField();
        JT_numero = new javax.swing.JTextField();
        JT_editora = new javax.swing.JTextField();
        JT_genero = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        Aluguel = new javax.swing.JMenu();
        Realizar_Aluguel = new javax.swing.JMenuItem();
        Realizar_Devolução = new javax.swing.JMenuItem();
        Menu_Livro = new javax.swing.JMenu();
        Cadastrar_Livro = new javax.swing.JMenuItem();
        Pesquisar_Livro = new javax.swing.JMenuItem();
        Editar_Livro = new javax.swing.JMenuItem();
        Excluir_Livro = new javax.swing.JMenuItem();
        Menu_Cliente = new javax.swing.JMenu();
        Cadastrar_Cliente = new javax.swing.JMenuItem();
        Pesquisar_Cliente = new javax.swing.JMenuItem();
        Editar_Cliente = new javax.swing.JMenuItem();
        Excluir_Cliente = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenu();

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Livro.png"))); // NOI18N
        jMenu5.setText("Livros");

        jMenuItem3.setText("Cadastrar Livro");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem6.setText("Pesquisar Livro");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem12.setText("Editar Livro");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem11.setText("Excluir Livro");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem7.setText("Cadastrar Aluguel");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Pesquisar Aluguel");
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user-male.png"))); // NOI18N
        jMenu3.setText("Clientes");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cadastrar cliente");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Pesquisar cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem9.setText("Editar cliente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Excluir cliente");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/16pdf.png"))); // NOI18N
        jMenu2.setText("Relatórios");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Livro.png"))); // NOI18N
        jMenuItem4.setText("Livros em acervo");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user-male.png"))); // NOI18N
        jMenuItem5.setText("Clientes");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close+door+exit+out+signout+icon-1320191203404268178.png"))); // NOI18N
        jMenu4.setText("Logout");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 346));
        setMinimumSize(new java.awt.Dimension(590, 346));
        setPreferredSize(new java.awt.Dimension(590, 346));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(54, 24, 20, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 30, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Autor :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 74, 38, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gêneros :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 124, 70, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Editora: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 74, 80, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ilustradores :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 170, 100, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero de livro :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 130, 100, 30);
        getContentPane().add(JT_nome);
        JT_nome.setBounds(200, 30, 310, 30);
        getContentPane().add(JT_autor);
        JT_autor.setBounds(340, 80, 170, 30);

        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(80, 30, 70, 30);
        getContentPane().add(JT_ilustrador);
        JT_ilustrador.setBounds(130, 180, 380, 30);
        getContentPane().add(JT_numero);
        JT_numero.setBounds(390, 130, 120, 30);
        getContentPane().add(JT_editora);
        JT_editora.setBounds(110, 80, 170, 30);
        getContentPane().add(JT_genero);
        JT_genero.setBounds(120, 130, 160, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 240, 100, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Pesquisar");
        jButton4.setEnabled(false);
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 240, 100, 40);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar");
        jButton3.setEnabled(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 240, 70, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Excluir");
        jButton1.setEnabled(false);
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 240, 80, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundinho.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, 0, 600, 310);

        Aluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/minuta2-saberimobiliario.png"))); // NOI18N
        Aluguel.setText("Aluguel");

        Realizar_Aluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home_icons_contract.png"))); // NOI18N
        Realizar_Aluguel.setText("Realizar Aluguel");
        Realizar_Aluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Realizar_AluguelActionPerformed(evt);
            }
        });
        Aluguel.add(Realizar_Aluguel);

        Realizar_Devolução.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/a-icon-04.png"))); // NOI18N
        Realizar_Devolução.setText("Realizar Devolução");
        Realizar_Devolução.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Realizar_DevoluçãoActionPerformed(evt);
            }
        });
        Aluguel.add(Realizar_Devolução);

        jMenuBar3.add(Aluguel);

        Menu_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Livro.png"))); // NOI18N
        Menu_Livro.setText("Livros");

        Cadastrar_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ec41c9bd80d6e07d3dfe3097fabac99d-abra-o-livro-aberto.png"))); // NOI18N
        Cadastrar_Livro.setText("Cadastrar Livro");
        Cadastrar_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Cadastrar_Livro);

        Pesquisar_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/71646d7673e8847ab07b3b7e78928777-icone-do-circulo-de-pesquisa.png"))); // NOI18N
        Pesquisar_Livro.setText("Pesquisar Livro");
        Pesquisar_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisar_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Pesquisar_Livro);

        Editar_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2186768.png"))); // NOI18N
        Editar_Livro.setText("Editar Livro");
        Editar_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Editar_Livro);

        Excluir_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4135100.png"))); // NOI18N
        Excluir_Livro.setText("Excluir Livro");
        Excluir_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Excluir_Livro);

        jMenuBar3.add(Menu_Livro);

        Menu_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user-male.png"))); // NOI18N
        Menu_Cliente.setText("Clientes");
        Menu_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ClienteMouseClicked(evt);
            }
        });
        Menu_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ClienteActionPerformed(evt);
            }
        });

        Cadastrar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/unnamed.png"))); // NOI18N
        Cadastrar_Cliente.setText("Cadastrar cliente");
        Cadastrar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cadastrar_ClienteMouseClicked(evt);
            }
        });
        Cadastrar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Cadastrar_Cliente);

        Pesquisar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/71646d7673e8847ab07b3b7e78928777-icone-do-circulo-de-pesquisa.png"))); // NOI18N
        Pesquisar_Cliente.setText("Pesquisar cliente");
        Pesquisar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisar_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Pesquisar_Cliente);

        Editar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Users-Edit-User-icon.png"))); // NOI18N
        Editar_Cliente.setText("Editar cliente");
        Editar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Editar_Cliente);

        Excluir_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/000000010.png"))); // NOI18N
        Excluir_Cliente.setText("Excluir cliente");
        Excluir_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Excluir_Cliente);

        jMenuBar3.add(Menu_Cliente);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close+door+exit+out+signout+icon-1320191203404268178.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenuBar3.add(Logout);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cadastrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Cadastro_Livro e = new Cadastro_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Cadastro_Cliente e = new Cadastro_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        Login e = new Login();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void Realizar_AluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Realizar_AluguelActionPerformed
        // TODO add your handling code here:
        Cadastro_Aluguel e = new Cadastro_Aluguel();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Realizar_AluguelActionPerformed

    private void Realizar_DevoluçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Realizar_DevoluçãoActionPerformed
        // TODO add your handling code here:
        Devolucao e = new Devolucao();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Realizar_DevoluçãoActionPerformed

    private void Cadastrar_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_LivroActionPerformed
        // TODO add your handling code here:
        Cadastro_Livro e = new Cadastro_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cadastrar_LivroActionPerformed

    private void Pesquisar_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisar_LivroActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Pesquisar_LivroActionPerformed

    private void Editar_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_LivroActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Editar_LivroActionPerformed

    private void Excluir_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_LivroActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Excluir_LivroActionPerformed

    private void Cadastrar_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cadastrar_ClienteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Cadastrar_ClienteMouseClicked

    private void Cadastrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_ClienteActionPerformed
        // TODO add your handling code here:
        Cadastro_Cliente e = new Cadastro_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cadastrar_ClienteActionPerformed

    private void Pesquisar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisar_ClienteActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Pesquisar_ClienteActionPerformed

    private void Editar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_ClienteActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Editar_ClienteActionPerformed

    private void Excluir_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_ClienteActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Excluir_ClienteActionPerformed

    private void Menu_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_ClienteMouseClicked

    private void Menu_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ClienteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_Menu_ClienteActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        Login e = new Login();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Livro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Livro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aluguel;
    private javax.swing.JMenuItem Cadastrar_Cliente;
    private javax.swing.JMenuItem Cadastrar_Livro;
    private javax.swing.JMenuItem Editar_Cliente;
    private javax.swing.JMenuItem Editar_Livro;
    private javax.swing.JMenuItem Excluir_Cliente;
    private javax.swing.JMenuItem Excluir_Livro;
    private javax.swing.JTextField JT_autor;
    private javax.swing.JTextField JT_editora;
    private javax.swing.JTextField JT_genero;
    private javax.swing.JTextField JT_ilustrador;
    private javax.swing.JTextField JT_nome;
    private javax.swing.JTextField JT_numero;
    private javax.swing.JMenu Logout;
    private javax.swing.JMenu Menu_Cliente;
    private javax.swing.JMenu Menu_Livro;
    private javax.swing.JMenuItem Pesquisar_Cliente;
    private javax.swing.JMenuItem Pesquisar_Livro;
    private javax.swing.JMenuItem Realizar_Aluguel;
    private javax.swing.JMenuItem Realizar_Devolução;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
