/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import java.awt.Toolkit;

/**
 *
 * @author aldac
 */
public class Tela_Principal extends javax.swing.JFrame {
    
    private void setIcon(){
            
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/icon.png")));
        
    }
   
    /**
     * Creates new form Tela_Principal_Gestor
     */
    public Tela_Principal() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Aluguel = new javax.swing.JMenu();
        Realizar_Aluguel = new javax.swing.JMenuItem();
        Realizar_Devolução = new javax.swing.JMenuItem();
        Menu_Livro = new javax.swing.JMenu();
        Cadastrar_Livro = new javax.swing.JMenuItem();
        Pesquisar_Livro = new javax.swing.JMenuItem();
        Editar_Livro = new javax.swing.JMenuItem();
        Excluir_Livro = new javax.swing.JMenuItem();
        Menu_Cliente = new javax.swing.JMenu();
        Cadastrar_Cliente = new javax.swing.JMenuItem();
        Pesquisar_Cliente = new javax.swing.JMenuItem();
        Editar_Cliente = new javax.swing.JMenuItem();
        Excluir_Cliente = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 518));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Seja bem vindo.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Tela Principal.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        Aluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/minuta2-saberimobiliario.png"))); // NOI18N
        Aluguel.setText("Aluguel");

        Realizar_Aluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home_icons_contract.png"))); // NOI18N
        Realizar_Aluguel.setText("Realizar Aluguel");
        Realizar_Aluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Realizar_AluguelActionPerformed(evt);
            }
        });
        Aluguel.add(Realizar_Aluguel);

        Realizar_Devolução.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/a-icon-04.png"))); // NOI18N
        Realizar_Devolução.setText("Realizar Devolução");
        Realizar_Devolução.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Realizar_DevoluçãoActionPerformed(evt);
            }
        });
        Aluguel.add(Realizar_Devolução);

        jMenuBar1.add(Aluguel);

        Menu_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Livro.png"))); // NOI18N
        Menu_Livro.setText("Livros");

        Cadastrar_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ec41c9bd80d6e07d3dfe3097fabac99d-abra-o-livro-aberto.png"))); // NOI18N
        Cadastrar_Livro.setText("Cadastrar Livro");
        Cadastrar_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Cadastrar_Livro);

        Pesquisar_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/71646d7673e8847ab07b3b7e78928777-icone-do-circulo-de-pesquisa.png"))); // NOI18N
        Pesquisar_Livro.setText("Pesquisar Livro");
        Pesquisar_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisar_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Pesquisar_Livro);

        Editar_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2186768.png"))); // NOI18N
        Editar_Livro.setText("Editar Livro");
        Editar_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Editar_Livro);

        Excluir_Livro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/4135100.png"))); // NOI18N
        Excluir_Livro.setText("Excluir Livro");
        Excluir_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_LivroActionPerformed(evt);
            }
        });
        Menu_Livro.add(Excluir_Livro);

        jMenuBar1.add(Menu_Livro);

        Menu_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user-male.png"))); // NOI18N
        Menu_Cliente.setText("Clientes");
        Menu_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ClienteMouseClicked(evt);
            }
        });
        Menu_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ClienteActionPerformed(evt);
            }
        });

        Cadastrar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/unnamed.png"))); // NOI18N
        Cadastrar_Cliente.setText("Cadastrar cliente");
        Cadastrar_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cadastrar_ClienteMouseClicked(evt);
            }
        });
        Cadastrar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Cadastrar_Cliente);

        Pesquisar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/71646d7673e8847ab07b3b7e78928777-icone-do-circulo-de-pesquisa.png"))); // NOI18N
        Pesquisar_Cliente.setText("Pesquisar cliente");
        Pesquisar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pesquisar_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Pesquisar_Cliente);

        Editar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Users-Edit-User-icon.png"))); // NOI18N
        Editar_Cliente.setText("Editar cliente");
        Editar_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Editar_Cliente);

        Excluir_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/000000010.png"))); // NOI18N
        Excluir_Cliente.setText("Excluir cliente");
        Excluir_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir_ClienteActionPerformed(evt);
            }
        });
        Menu_Cliente.add(Excluir_Cliente);

        jMenuBar1.add(Menu_Cliente);

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close+door+exit+out+signout+icon-1320191203404268178.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(Logout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        Login e = new Login();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void Menu_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_ClienteMouseClicked

    private void Menu_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ClienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Menu_ClienteActionPerformed

    private void Cadastrar_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cadastrar_ClienteMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Cadastrar_ClienteMouseClicked

    private void Cadastrar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_ClienteActionPerformed
        // TODO add your handling code here:
         Cadastro_Cliente e = new Cadastro_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cadastrar_ClienteActionPerformed

    private void Pesquisar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisar_ClienteActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Pesquisar_ClienteActionPerformed

    private void Cadastrar_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_LivroActionPerformed
        // TODO add your handling code here:
        Cadastro_Livro e = new Cadastro_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Cadastrar_LivroActionPerformed

    private void Pesquisar_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pesquisar_LivroActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Pesquisar_LivroActionPerformed

    private void Editar_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_LivroActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Editar_LivroActionPerformed

    private void Excluir_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_LivroActionPerformed
        // TODO add your handling code here:
        Pesquisa_Livro e = new Pesquisa_Livro();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Excluir_LivroActionPerformed

    private void Editar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_ClienteActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Editar_ClienteActionPerformed

    private void Excluir_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir_ClienteActionPerformed
        // TODO add your handling code here:
        Pesquisa_Cliente e = new Pesquisa_Cliente();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Excluir_ClienteActionPerformed

    private void Realizar_AluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Realizar_AluguelActionPerformed
        // TODO add your handling code here:
        Cadastro_Aluguel e = new Cadastro_Aluguel();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Realizar_AluguelActionPerformed

    private void Realizar_DevoluçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Realizar_DevoluçãoActionPerformed
        // TODO add your handling code here:
        Devolucao e = new Devolucao();
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_Realizar_DevoluçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Aluguel;
    private javax.swing.JMenuItem Cadastrar_Cliente;
    private javax.swing.JMenuItem Cadastrar_Livro;
    private javax.swing.JMenuItem Editar_Cliente;
    private javax.swing.JMenuItem Editar_Livro;
    private javax.swing.JMenuItem Excluir_Cliente;
    private javax.swing.JMenuItem Excluir_Livro;
    private javax.swing.JMenu Logout;
    private javax.swing.JMenu Menu_Cliente;
    private javax.swing.JMenu Menu_Livro;
    private javax.swing.JMenuItem Pesquisar_Cliente;
    private javax.swing.JMenuItem Pesquisar_Livro;
    private javax.swing.JMenuItem Realizar_Aluguel;
    private javax.swing.JMenuItem Realizar_Devolução;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
